### ISSUE TITLE
Notebook links not converted correctly

### ISSUE THREAD

**Issue by ketch** [takluyver/bookbook#4]
I'm having trouble with the treatment of links to notebooks in latex output.  No matter what I do, running bookbook just converts them to hyperlinks (`\href`).

If I make a test markdown file with a link like

    [link](01-notebook.ipynb)

and run

    pandoc --filter ./filter_links.py -f markdown -t latex test.md

it works fine; I get `Section \ref{sec:01-notebook}` as expected.  I've also tried patching nbconvert by pasting bookbook's `filter_links.py` code into nbconvert's version, and then running nbconvert on a notebook with links; that works correctly.

It seems to me like the `convert_link` code in bookbook simply never gets called.  Do you have a working example so that I could verify whether the problem is with my setup?

**Comment by ketch** [comment]
I wonder if https://github.com/jupyter/nbconvert/commit/178ce3d31c92d06a4294634f12c8cc393db37216 could possibly have broken this?

**Comment by takluyver** [comment]
Yep, I think one of those changes in nbconvert has indeed broken bookbook. Specifically, I think it's a change to the template that makes it no longer use the Jinja filter bookbook overrides.

**Comment by ketch** [comment]
I've tried patching it but so far without success.

**Comment by takluyver** [comment]
Have a go with that. You may need to update the `pandocfilters` package.

**Comment by ketch** [comment]
Thanks for the help.  Somehow it still does not work for me.  It must be a problem with my setup, because the test also fails on my system.

**Comment by ketch** [comment]
I got things working, as noted in my comment on https://github.com/takluyver/bookbook/issues/5.  Thanks again, and many thanks for creating this!  It has been very useful.  In case you're interested, the project I'm using it for is here (it's somewhat of a mess at the moment):

https://github.com/clawpack/riemann_book

**Comment by takluyver** [comment]
Great, thanks for helping to track down bugs in experimental code :-)
