### ISSUE TITLE
References not converted to latex when template extends report.tplx

### ISSUE THREAD

**Issue by ketch** [takluyver/bookbook#5]
If one uses bookbook.latex with a template that starts with

    ((*- extends 'report.tplx' -*))

then cross references are not properly converted to latex; they are simply formatted as hyperlinks with \href{}.  This seems to be caused by the following section of nbconvert/templates/latex/report.tplx:

```
((* block markdowncell scoped *))
((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown', 'latex', extra_args=["--chapters"]) )))
((* endblock markdowncell *))
```

**Comment by ketch** [comment]
As a hacky workaround, I've copied `filter_links.py` to my book directory and set

```
((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown', 'latex', extra_args=["--chapters",'--filter', './filter_links.py']) )))
```

in my template.

**Comment by takluyver** [comment]
Aha, I hadn't noticed that `report.tplx` overrides the markdowncell definition. That probably means there's a bug in nbconvert as well.

**Comment by takluyver** [comment]
This should work with the development version of nbconvert, or 5.2 when we release it.
